import Head from "next/head"
import { useSession } from "next-auth/react"

export default function Home() {
	const { data: session } = useSession()

	return (
		<>
			<Head>
				<title>ホーム</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="text-3xl font-bold ">ホーム</h1>
			{session ?? <div>ようこそ{session}</div>}
		</>
	)

	// const Login = ({ user }) => {
	// 	return (
	// 		<>
	// 			<div></div>
	// 		</>
	// 	)
	// }
}
