import Head from "next/head"
import { signOut, useSession } from "next-auth/react"
import Login from "../src/components/login"
import Home from "../src/components/home"

export default function Index() {
	const { data: session } = useSession()

	console.log(session)

	return (
		<>
			<Head>
				<title>ホーム</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{!session ? (
				<Login />
			) : (
				<>
					<Home user={session?.user} />
				</>
			)}
		</>
	)
}
